FROM ubuntu:24.04

RUN apt-get update && \
	apt-get -y upgrade && \
	apt-get install -y software-properties-common && \
	apt-get install -y python3 python3-pip graphviz unzip zip curl jq wget bc fonts-dejavu-core util-linux && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

RUN pip3 install --break-system-packages -Iv \
	anytree \
	pydot \
	reportlab \
	goatools

COPY code.zip /opt
WORKDIR /opt
RUN unzip code.zip && rm code.zip
RUN chmod -R 777 *

ENTRYPOINT ["./run.sh"]
