; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                        = 10180924-x86_64 Linux     
[ DataSettings ]
datatype                   = snDistance                
MissingBaseSymbol          = ?                         
IdenticalBaseSymbol        = .                         
GapSymbol                  = -                         
[ ProcessTypes ]
ppInfer                    = true                      
ppUPGMA                    = true                      
[ AnalysisSettings ]
Analysis                   = Phylogeny Reconstruction  
Scope                      = All Selected Taxa         
Statistical Method         = UPGMA                     
System Resource Usage      = ====================      
Number of Threads          = 1                         
Has Time Limit             = False                     
Maximum Execution Time     = -1                        
