FROM pegi3s/docker:29.0.1
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update --fix-missing
RUN apt-get install python3 && apt-get install -y python3-pip
RUN apt-get -y install libmpv2 && ln -s /lib/x86_64-linux-gnu/libmpv2.so.2 /lib/x86_64-linux-gnu/libmpv2.so.1 && ldconfig

RUN apt-get -y install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio libgtk-3-0 zenity firefox



RUN apt-get -y install graphviz
RUN python3 -m pip install --break-system-packages flet graphviz

COPY for_build/gui.py scripts/
COPY for_build/main.py scripts/
COPY for_build/tools_compatibility.json scripts/
COPY for_build/tools_images.json scripts/
COPY for_build/tools_help.json scripts/

ENTRYPOINT ["python3", "scripts/gui.py"]
