#!/bin/bash

#### supported methods are: scriber ispred4 sppider cons_ppisp meta_ppisp predictprotein psiver csm_potential scannet whiscy predus2 ####

. /data/config

prefix=""

for single_method in $method; do
	uppercase_method=$(echo "$single_method" | tr '[:lower:]' '[:upper:]')
	wait_interval="${single_method}wi" 
	if [ -v "$wait_interval" ]; then
		var="${uppercase_method}_WAIT_INTERVAL"
    	env1=""$var"="${!wait_interval}""
	fi
	num_retries="${single_method}nr"
	if [ -v "$num_retries" ]; then
		var="${uppercase_method}_NUM_RETRIES" 
    	env2=""$var"="${!num_retries}""
	fi
	prefix="$prefix $env1 $env2"
done

ls /data/$input_dir > /output/list
while read name; do
	protein_dir=/output/${name%.*}
	
	if [ ! -d "$protein_dir" ]; then
		mkdir -p "$protein_dir"
	fi

	grep "^ATOM" /data/$input_dir/$name > /output/tmp0.pdb
	protein_size=$(tail -1 /output/tmp0.pdb | cut -c 23-26 | sed 's/ //g')
	
	for single_method in $method; do
		
		#Needs extension
		command_with_env="${prefix} cport /output/tmp0.pdb $chain --pred $single_method"
		eval $command_with_env 

		if [ $? -ne 0 ]; then
			echo "The program ended with an error."
			continue
		else
			cp /output/predictors_tmp0.csv $protein_dir/"${name%.*}".$single_method.csv 
			touch /output/$name.result && cp /output/predictors_tmp0.csv /output/$name.result && rm /output/predictors_tmp0.csv
		fi

		position=1
		while [ $position -le $protein_size ]; do
			sed -i "s/$/\,\-/g" /output/$name.result
			position=$(( $position +1 ))
		done
		ct=$(( $protein_size + 1 ))
		cut -f1-$ct -d',' /output/$name.result > /output/$name.result_a && cat /output/$name.result_a > /output/$name.result && rm /output/$name.result_a
		
		position=1
		while [ $position -le $protein_size ]; do
			echo $position >> /output/position
			position=$(( $position +1 ))
		done
		
		header=$(cat /output/position | tr '\n' ',')
		echo "Position,"$header >> /output/$name.final_result_position
		
		while read current_line; do
			read next_line
			
			b=1
			a=$(echo $current_line | cut -f2 -d',')
			while [ $a -gt $b ]; do
				c=$(echo $c"-,")
				d=$(echo $next_line | cut -f2- -d',')
				e=$(echo $next_line | cut -f1 -d',')
				b=$(( b + 1 ))
			done 
			
			if [ $a -ne "1" ]; then #no equals
				modified_line=$(echo $e","$c$d)
				next_line=$modified_line
			fi
			a=1; b=1; c=""; d=""; e=""
			
			echo $next_line >> /output/$name.final_result
		done < /output/$name.result

		cut -f1-$ct -d',' /output/$name.final_result > /output/$name.final_result_a && 
			cat /output/$name.final_result_position /output/$name.final_result_a > /output/$name.final_result.csv && 
			rm /output/$name.final_result_position /output/$name.final_result_a /output/$name.final_result
		
		f=$(cat /output/$name.final_result.csv | wc -l)
		#transpose file
		sed 's/\,/ /g' /output/$name.final_result.csv | awk '
		{ 
			for (i=1; i<=NF; i++)  {
				a[NR,i] = $i
			}
		}
		NF>p { p = NF }
		END {    
			for(j=1; j<=p; j++) {
				str=a[1,j]
				for(i=2; i<=NR; i++){
					str=str","a[i,j];
				}
				print str
			}
		}' >  $protein_dir/"${name%.*}".$single_method.result.csv

		initial=$protein_dir/"${name%.*}".$single_method.result.csv
		output=$protein_dir/"${name%.*}".$single_method.result.cat.csv
		head -n 1 $initial > $output

		tail -n +2 $initial | awk -v method="$single_method" -F, '
			function adjust_sppider(value) {
				return value == "A"? 1: value
			}
			function adjust_ispred4(value) {
				return value >= 0.5 ? 1: value < 0.5 ? 2: value
			}
			function adjust_psiver(value) {
				return value >= 0.5? 1 : value <= 0.37? 2 : value > 0.37 && value < 0.5? 0 : value
			}
			function adjust_scannet(value) {
				return value < 0.35 ? 2 : value >= 0.35 && value < 0.5 ? 0 : value >= 0.5 ? 1: value
			}
			function adjust_scriber(value) {
				return value < 0.27 ? 2 : value >= 0.27 && value < 0.5 ? 0 : value >= 0.5 ? 1: value
			}
			{
			if ($2 ~ /^[0-9]*\.?[0-9]+$/) {
				if (method == "sppider") {
					$2 = adjust_sppider($2)			
				} else if (method == "psiver") {
					$2 = adjust_psiver($2)
				} else if (method == "ispred4") {
					$2 = adjust_ispred4($2)
				} else if (method == "scannet") {
					$2 = adjust_scannet($2)
				} else if (method == "scriber") {
					$2 = adjust_scriber($2)
				}
			}
			print $1 "," $2
		}'  | sed 's/,-/,0/g'  >> $output

		rm /output/$name.final_result.csv
		rm /output/position
	done
	rm /output/$name.result
	rm /output/tmp0.pdb
done < /output/list
rm /output/list