"""URLs used by CPORT."""
WHISCY_URL = "https://wenmr.science.uu.nl/whiscy/"
SCRIBER_URL = "https://biomine2.cs.vcu.edu/servers/SCRIBER/"
ISPRED4_URL = "https://ispred4.biocomp.unibo.it/ispred/default/"
SPPIDER_URL = "https://sppider.cchmc.org"
CONS_PPISP_URL = "https://pipe.rcc.fsu.edu/ppisp.html"
META_PPISP_URL = "https://pipe.rcc.fsu.edu/meta-ppisp.html"
PREDUS2_URL = "https://honiglab.c2b2.columbia.edu/hfpd/html/predus.html"
PREDICTPROTEIN_URL = "https://predictprotein.org"
PREDICTPROTEIN_API = "https://predictprotein.org/api/ppc_fetch"
PSIVER_URL = "https://psiver.mizuguchilab.org/PSIVER/"
CSM_POTENTIAL_URL = "https://biosig.lab.uq.edu.au/csm_potential/api/predict"
SCANNET_URL = "https://bioinfo3d.cs.tau.ac.il/ScanNet/index_real.html"
PDB_URL = "https://files.rcsb.org/download/"
PDB_FASTA_URL = "https://www.rcsb.org/fasta/entry/"
