#!/bin/bash

if [ -z ${VERSION} ]; then 
    echo "VERSION environment variable not set."
    exit 1
else
    echo "Building ${VERSION}"
    docker build -f ${DOCKERFILE_PATH} --build-arg VERSION=${VERSION} -t ${IMAGE_NAME} .
fi
