import sys
import re
import warnings

# Suppress the use_reentrant warning before running the script
warnings.filterwarnings("ignore", message=".*use_reentrant.*")

# Receive the working directory as an argument
data_path = sys.argv[1]

# Read the script generated by nbconvert
with open('/app/pesto/apply_model.py', 'r') as f:
    script = f.read()

# Replace data_path so it points to the temporary folder
script = re.sub(
    r'data_path\s*=\s*["\'].*?["\']',
    f'data_path = "{data_path}"',
    script
)

# Run the modified script
exec(compile(script, 'apply_model.py', 'exec'))