#!/bin/bash

OUTDIR=${1:-/data}
echo "Running..."
echo "outdir=" $OUTDIR
fields=$(cat $OUTDIR/parameters.sppider)
echo "Parameters: " $fields
mkdir $OUTDIR/results
for f in $OUTDIR/*.pdb
do
	a="$(basename -- $f)"
	echo "Submitting " $a
	curl -F PDBFileName="@/$f" $fields https://sppider.cchmc.org/cgi-bin/int_recognition.cgi > $OUTDIR/results/$a.result.sppider
	sleep 20
done
