#!/bin/bash

display_usage() { 
  echo -e "This script lists the number of pulls of each image for a given Docker Hub user."
  echo -e "\nUsage:"
  echo -e "\tUsage: `basename $0` <docker-hub-user> [-jq=</path/to/jq>] [-ps/--page-size=<page-size>]"
} 

if [[ $1 == "--help" ]]; then
    display_usage
    exit 0
fi

if [ $# -lt 1 ] && [ $# -gt 3 ]; then
    tput setaf 1
    echo -e "Error. This script requires one, two or three arguments.\n"
    tput sgr0
    display_usage
    exit 1
fi

USER=$1

PAGE_SIZE=100
JQ=jq-linux64

for key in "$@"
do
case $key in
    -jq=*|--option=*)
    JQ="${key#*=}"
    shift
    ;;
    -ps=*|--page-size=*)
    PAGE_SIZE="${key#*=}"
    shift
    ;;
    *)
      # unknown option
    ;;
esac
done

if ! [ -x "$(command -v $JQ)" ]; then
    tput setaf 1
    echo -e "Error. The jq executable is not available: $JQ.\n"
    tput sgr0
    exit 1
fi

NEXT="https://hub.docker.com/v2/repositories/$USER/?page_size=$PAGE_SIZE"

while [ "$NEXT" != "null" ]; do
  tmpFile=$(mktemp)
  wget -q "$NEXT" -O $tmpFile

  NEXT=$(cat $tmpFile | $JQ --raw-output '.next')

  RESULTS=$(cat $tmpFile | $JQ '.results | length')

  RESULTS=$(expr $RESULTS - 1)

  for i in $(seq 0 $RESULTS); do
   im=$(cat $tmpFile | $JQ --raw-output ".results[$i].name, .results[$i].pull_count" | tr '\n' ' ')
   echo $im
  done

  rm $tmpFile
done
