#!/bin/bash

function printHelp {
  echo -e "This script replaces the sequence headers using the provided mapping file (with input headers in the first column and new headers in the second)."
  echo -e "\nUsage:"
  echo -e "\t`basename $0` </path/to/input_fasta> </path/to/headers_map_file> </path/to/outut/fasta>"
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  printHelp
  exit 0
fi

if [ ! $# -eq 3 ]; then
  tput setaf 1
  echo -e "Error. This script requires three arguments.\n"
  tput sgr0
  printHelp
  exit 1
fi

rm -f $3

while IFS= read -r line || [ -n "$line" ]; do
  if [[ $line = \>* ]] ; then
    line_regex=$(echo $line | sed 's/\[/\\[/g; s/\]/\\]/g; s#(#\\(#; s#)#\\)#')
    original_header=$(cat $2 | grep -P "^${line_regex}\t" | cut -f2)
    if [ -z "$original_header" ]
    then
      echo "$line" >> $3
    else
      echo $original_header >> $3
    fi
  else
    echo "$line" >> $3
  fi
done < "$1"
